branches:
  only:
    - master
sudo: required
dist: trusty
language: python
python:
  - 3.4
jdk:
  - openjdk7
before_script:
  - sudo apt-get update -qq
  - sudo bash ./deploy/provision.sh

after_success:
notifications:
  email: false
